# This is the definitive render.yaml configuration

# We first define the buildpack we need globally
buildpacks:
  - https://github.com/jontewks/puppeteer-heroku-buildpack

# Then we define our service
services:
  - type: web
    name: yt-teacher-backend
    env: node
    plan: free
    # We point the build command to our new script
    buildCommand: "./render-build.sh"
    startCommand: "node server.js"
    healthCheckPath: /